[package]
name = "mime-db"
version = "0.1.2"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
edition = "2018"
description = "Media Type Database, looks up `extension` or `media type`."
keywords = ["mime", "media-extensions", "media-types"]
repository = "https://github.com/trek-rs/mime-db"
readme = "README.md"
license = "MIT/Apache-2.0"

[build-dependencies]
surf = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies.async-std]
version = "1.2"
features = ["attributes"]